$(document).ready(function(){
  $('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:3,
            nav:false
        },
        1000:{
            items:5,
            nav:true,
            loop:false
        },
        1200:{
            items:5,
            nav:true,
            loop:false
        },
        1400:{
            items:5,
            nav:true,
            loop:false
        },
        1600:{
            items:5,
            nav:true,
            loop:false
        },
        1800:{
            items:5,
            nav:true,
            loop:false
        },
        2000:{
            items:5,
            nav:true,
            loop:false
        }
    }
  })
});